RUN pip install --no-cache-dir -U pip
RUN pip install --no-cache-dir -e /app/bisheng-langchain
RUN pip install --no-cache-dir -r /app/bisheng/requirements.txt
RUN pip install --no-cache-dir "pypdf>=3.0.0,<4.0.0" "llama-index==0.9.48"